#!/usr/bin/env bash
#A script that creates a file /var/run/holbertonscript.pid containing the script PID and also does the following:
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" upon receiving a SIGTERM
# displays "Y U no love me?!" upon receiving a SIGINT
# deletes the file /var/run/holbertonscript.pid and terminates upon
#+ receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/holbertonscript.pid
    exit
    }

echo "$$" > /var/run/holbertonscript.pid

while true
do
  echo "To infinity and beyond"
    sleep 2
      trap 'echo "Y U no love me?!"' SIGINT
        trap 'echo "I hate the kill command" && terminator' SIGTERM
	  trap 'terminator' SIGQUIT
	  done
	  