#!/usr/bin/env bash
#A script that creates a file /var/run/holbertonscript.pid containing the script PID and also does the following:
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" upon receiving a SIGTERM
# displays "Y U no love me?!" upon receiving a SIGINT
# deletes the file /var/run/holbertonscript.pid and terminates upon
#+ receiving a SIGQUIT or SIGTERM.

sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
    done
