#!/usr/bin/env bash
#A script that creates a file /var/run/holbertonscript.pid containing the script PID and also does the following:
# displays "To infinity and beyond" indefinitely
# displays "I hate the kill command" upon receiving a SIGTERM
# displays "Y U no love me?!" upon receiving a SIGINT
# deletes the file /var/run/holbertonscript.pid and terminates upon
#+ receiving a SIGQUIT or SIGTERM.

FILE="/var/run/holbertonscript.pid"
echo "$$" > $FILE

trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
while true; do
    echo "To infinity and beyond"
    sleep 2
done
